### ISSUE TITLE
Improper Import

### ISSUE THREAD

**Issue by Professor-Control** [Toontown-Mystery/Toontown-Mystery#4]
My AI is repeatedly crashing while trying to import something that's invalid.
`Traceback (most recent call last):
  File "C:\Users\-----\Documents\GitHub\Toontown-Mystery\panda\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\-----\Documents\GitHub\Toontown-Mystery\panda\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\-----\Documents\GitHub\Toontown-Mystery\toontown\ai\AIStart.py", line 48, in <module>
    from toontown.ai.ToontownAIRepository import ToontownAIRepository
  File "toontown\ai\ToontownAIRepository.py", line 33, in <module>
    from toontown.hood.BossbotHQDataAI import BossbotHQDataAI
  File "toontown\hood\BossbotHQDataAI.py", line 14, in <module>
    from toontown.coghq import DistributedCogKartAI
  File "toontown\coghq\DistributedCogKartAI.py", line 2, in <module>
    from toontown.safezone import DistributedGolfKartAI
  File "toontown\safezone\DistributedGolfKartAI.py", line 13, in <module>
    from toontown.golf import GolfManagerAI
  File "toontown\golf\GolfManagerAI.py", line 5, in <module>
    from toontown.golf import DistributedGolfCourseAI
  File "toontown\golf\DistributedGolfCourseAI.py", line 4, in <module>
    from toontown.golf import DistributedGolfHoleAI
  File "toontown\golf\DistributedGolfHoleAI.py", line 5, in <module>
    import DistributedPhysicsWorldAI
  File "toontown\golf\DistributedPhysicsWorldAI.py", line 9, in <module>
    from toontown.golf import PhysicsWorldBase
  File "toontown\golf\PhysicsWorldBase.py", line 8, in <module>
    from toontown.minigame import ArrowKeys
  File "toontown\minigame\ArrowKeys.py", line 1, in <module>
    from pandac.PandaModules import ModifierButtons
ImportError: No module named pandac.PandaModules`

**Comment by 2Epik4u** [comment]
pandac.PandaModules is old and isnt being used anymore use panda3d.core instead
